---
abstract: 'Parse the Branch CRD Report'
author:
  - 'Guillermo Roditi (groditi) <groditi@cpan.org>'
build_requires:
  FindBin: 0
  Path::Class: 0
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-FINRA-File-PostBranchIndividualReport
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Path::Class: 0
  XML::LibXML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001000
